# Properties of Dot Product - Lab

## Introduction

In this lab, you'll be practicing some interesting properties of a Dot Product-type matrix multiplication. Understanding these properties will become useful as you move forward with machine learning. The lab will require you to calculate results to provide a proof for these properties.

## Objectives
You will be able to:
* Understand and analytically explain Distributive, Commutative and Associative properties of dot product

## Instructions

* For each property, create suitably sized matrices with random data and prove the equations 
* Ensure that size/dimension assumptions are met while performing calculations (you'll see errors otherwise)
* Calculate the LHS and RHS for all equations and show if they are equal or not

## Distributive Property - matrix multiplication is distributive

### Prove that $A \cdot (B+C) = (A \cdot B + A \cdot C) $

In [1]:
import numpy as np

In [5]:
np.random.randint(5,size=(3,3))

array([[4, 2, 2],
       [1, 1, 4],
       [1, 0, 4]])

In [7]:
A = np.random.randint(5,size=(3,2))
B = np.random.randint(5,size=(2,3))
C = np.random.randint(5,size=(2,3))

print(A)
print(B)
print(C)
print(np.dot(A,(B+C)))
print(np.dot(A,B)+np.dot(A,C))
print(np.dot(A,(B+C)) == np.dot(A,B)+np.dot(A,C))

[[4 0]
 [3 3]
 [2 0]]
[[0 2 1]
 [3 0 4]]
[[2 0 4]
 [0 0 2]]
[[ 8  8 20]
 [15  6 33]
 [ 4  4 10]]
[[ 8  8 20]
 [15  6 33]
 [ 4  4 10]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


## Associative Property - matrix multiplication is associative
### Prove that $A \cdot (B \cdot C) = (A \cdot B) \cdot C $

In [2]:
A = np.random.randint(5,size=(3,2))
B = np.random.randint(5,size=(2,3))
C = np.random.randint(5,size=(2,3))

print(A)
print(B)
print(C)
print(np.dot(A,np.dot(B,C))
print(np.dot(np.dot(A, B),C)
print(np.dot(A,(B+C)) == np.dot(A,B)+np.dot(A,C))

## Commutative Property - matrix multiplication is NOT commutative
### Prove that for matrices, $A \cdot B \neq B \cdot A $

In [3]:
# Your code here 

## Commutative Property -  vector multiplication IS commutative
### Prove that for vectors,  $x^T \cdot y = y^T \cdot x$
Note: superscipt<sup>T</sup> denotes the transpose we saw earlier

In [4]:
# Your code here 

## Simplification of the matrix product
### Prove that $ (A \cdot B)^T = A^T \cdot B^T $

In [5]:
# Your code here 

## Summary 

You've seen enough matrix algebra by now to solve a problem of linear equations as you saw earlier. You'll now see how to do this next. 