# Properties of Dot Product - Lab

## Introduction

In this lab, you'll be practicing some interesting properties of a Dot Product-type matrix multiplication. Understanding these properties will become useful as you move forward with machine learning. The lab will require you to calculate results to provide a proof for these properties.

## Objectives
You will be able to:
* Understand and analytically explain Distributive, Commutative and Associative properties of dot product

## Instructions

* For each property, create suitably sized matrices with random data and prove the equations 
* Ensure that size/dimension assumptions are met while performing calculations (you'll see errors otherwise)
* Calculate the LHS and RHS for all equations and show if they are equal or not

## Distributive Property - matrix multiplication is distributive

### Prove that $A \cdot (B+C) = (A \cdot B + A \cdot C) $

In [1]:
import numpy as np

In [4]:
np.random.randint(3,3)

ValueError: Range cannot be empty (low >= high) unless no samples are taken

In [3]:
A = np.random.rand(3,2)
B = np.random.rand(2,3)
C = np.random.rand(2,3)

print(A)
print(B)
print(C)
print(np.dot(A,(B+C)))
print(np.dot(A,B)+np.dot(A,C))

[[0.93803194 0.00281178]
 [0.58909377 0.54309888]
 [0.82636631 0.1009761 ]]
[[0.02472076 0.84973601 0.84299488]
 [0.58360429 0.72820158 0.80242026]]
[[0.25709942 0.39423306 0.50102615]
 [0.62951952 0.75149055 0.06974811]]
[[0.26776735 1.17104328 1.263187  ]
 [0.82486469 1.53643357 1.26542809]
 [0.35538321 1.17738767 1.19872186]]
[[0.26776735 1.17104328 1.263187  ]
 [0.82486469 1.53643357 1.26542809]
 [0.35538321 1.17738767 1.19872186]]


In [1]:
# Your code here

## Associative Property - matrix multiplication is associative
### Prove that $A \cdot (B \cdot C) = (A \cdot B) \cdot C $

In [2]:
# Your code here 

## Commutative Property - matrix multiplication is NOT commutative
### Prove that for matrices, $A \cdot B \neq B \cdot A $

In [3]:
# Your code here 

## Commutative Property -  vector multiplication IS commutative
### Prove that for vectors,  $x^T \cdot y = y^T \cdot x$
Note: superscipt<sup>T</sup> denotes the transpose we saw earlier

In [4]:
# Your code here 

## Simplification of the matrix product
### Prove that $ (A \cdot B)^T = A^T \cdot B^T $

In [5]:
# Your code here 

## Summary 

You've seen enough matrix algebra by now to solve a problem of linear equations as you saw earlier. You'll now see how to do this next. 